version: '3.7'
volumes:
  pgdata:
    name: pgdata_jochre
services:
  postgres:
    image: postgres:15.3-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: jochre
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jochre_search
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
  postgres-test:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: jochre
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jochre_search_test
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
  keycloak:
    build:
      context: ./
      dockerfile: keycloak-with-test-realm.Dockerfile
    environment:
      KEYCLOAK_IMPORT: /realm.json
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KEYCLOAK_HTTP_PORT: 8080
      DB_VENDOR: h2
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
    
