addSbtPlugin("com.github.sbt"            % "sbt-native-packager" % "1.9.16")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo"       % "0.10.0")
addSbtPlugin("com.github.sbt"            % "sbt-pgp"             % "2.2.1")
addSbtPlugin("org.xerial.sbt"            % "sbt-sonatype"        % "3.9.21")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.5.2")